name: CI Demo

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    # gets your repo files into the runner

      - name: Say hello
        run: echo "Hello, CI with GitHub Actions!"
