name: CI Demo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ] && [ -s requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No dependencies to install."
          fi

      - name: Run tests
        run: python -m unittest discover -v
