name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 * * *"   # Every day at 00:00 UTC

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scheduled message
        run: echo "Scheduled build completed successfully!"
